from typing import Protocol

from smartbot.core.interfaces import Message


class BaseProvider(Protocol):
    "Abstract class for define a common interfaz for any provider"

    def __init__(self) -> None:
        """
        Init the provider with the optional configuration

        """
        ...

    def generate_response(self, prompt:Message, history: list[dict[str,str]])-> Message:
        """
        Generate a response based on user input and history.


        :param prompt: The current user message
        :type prompt: str
        :param history: List of messages, a message typically looks
        like = {"role": "user", "content": "hello"}
        :type history: list[dict[str, str]]
        :return: The response generated by the LLM
        :rtype: str
        """
        ...

    def validate_config(self)-> bool:
        """Validates if the configuration exists.

        :return: The response generated by the LLM
        :rtype: str
        """
        ...

