from abc import ABC , abstractmethod

class BaseProvider(ABC):
    "Abstract class for define a common interfaz for any provider"

    def __init__(self, config: dict[str,str]|None) -> None:
        """
        Init the provider with the optional configuration

        :param config: Dictionary with api_keys, URLs, models, temperature, ...
        :type config: Dict[str, str] | None
        """
        super().__init__()
    @abstractmethod
    def generate_response(self, prompt:str, history: list[dict[str,str]])-> str:
        """
        Generate a response based on user input and history.


        :param prompt: The current user message
        :type prompt: str
        :param history: List of messages, a message typically looks like = {"role": "user", "content": "hello"}
        :type history: list[dict[str, str]]
        :return: The response generated by the LLM
        :rtype: str
        """
        pass
    @abstractmethod
    def validate_config(self)-> bool:
        """Validates if the configuration exists.

        :return: The response generated by the LLM
        :rtype: str
        """
        pass